# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='codified_time',
            new_name='modified_time',
        ),
    ]
